mas_position_offboard_mxsitl:
  ros__parameters:
    agent_ns: ["px4_1", "px4_2", "px4_3", "px4_4", "px4_5", "px4_6", "px4_7"]
    formation: [
    "2.0*np.cos(np.pi/180*60)","2.0*np.sin(np.pi/180*60)","-0.5",
    "2.0*np.cos(np.pi/180*180)","2.0*np.sin(np.pi/180*180)","-0.5",
    "2.0*np.cos(np.pi/180*300)","2.0*np.sin(np.pi/180*300)","-0.5",
    "2.0*np.cos(np.pi/180*0)","2.0*np.sin(np.pi/180*0)","-0.65",
    "2.0*np.cos(np.pi/180*120)","2.0*np.sin(np.pi/180*120)","-0.65",
    "2.0*np.cos(np.pi/180*240)","2.0*np.sin(np.pi/180*240)","-0.65",
    "0.0","0.0","-0.1"
    ]
    formation_seq: ["-1"]
    adjacency: [
    "0","1","1","1","1","1","1",
    "1","0","1","1","1","1","1",
    "1","1","0","1","1","1","1",
    "1","1","1","0","1","1","1",
    "1","1","1","1","0","1","1",
    "1","1","1","1","1","0","1",
    "1","1","1","1","1","1","0"
    ]